### ISSUE TITLE
Switch to npm caching built into actions/setup-node

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-iteration-template#714]
In our GitHub Actions workflows we currently use `actions/cache` to cache npm stuff. This functionality has been integrated into `actions/setup-node`: https://github.com/actions/setup-node#caching-packages-dependencies.

We can replace the `actions/cache` step by changing our `actions/setup-node` step to:
```yml
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: '**/package-lock.json'
```
